=== dohughes-msft/azure-public/rge/agps/schema/query.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "id",
            "label",
            "description",
            "usecases",
            "table",
            "queryBody"
        ],
        "properties": {
            "id": {
                "type": "string"
            },
            "label": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "usecases": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "table": {
                "type": "string"
            },
            "queryBody": {
                "type": "string"
            }
        },
        "additionalProperties": false
    }
}

=== dohughes-msft/azure-public/rge/agps/kql-json/manageddisk.json
[
    {
        "id": "mdsk01",
        "label": "ManagedDiskVM",
        "description": "Azure Managed Disks",
        "usecases": [
            "WAPA",
            "AGPS"
        ],
        "table": "resources",
        "queryBody": "| extend lowerId = tolower(id) | join kind=inner (resources | where type == 'microsoft.compute/disks' | extend diskSku = tostring(sku.name) | project diskName = name, diskSku, vmId = tolower(managedBy), sizeGb = properties.diskSizeGB) on $left.lowerId == $right.vmId | project-away vmId | project subscriptionId, vmName = name, location, diskName, diskSku, sizeGb, tags"
    },
    {
        "id": "mdsk02",
        "label": "ManagedDiskSKU",
        "description": "Count disks by SKU",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.compute/disks' | project id, sku = tostring(sku.name), env = tostring(tags.environment) | summarize count() by env, sku | order by count_ desc"
    },
    {
        "id": "mdsk03",
        "label": "UnattachedManagedDisks",
        "description": "Unattached Managed Disks",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.compute/disks' | where properties.diskState =~ \"unattached\" | extend subId = split(id, \"/\", 2)[0], resourceGroup = split(id, \"/\", 4)[0] | project subId, resourceGroup, name, sku.name, properties.diskSizeGB"
    },
    {
        "id": "mdsk04",
        "label": "DiskCountByVM",
        "description": "Disk count by VM",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | extend lowerId = tolower(id) | join kind=inner (Resources | where type =~ 'Microsoft.Compute/disks' | project disk = name, vm = tolower(tostring(managedBy)) ) on $left.lowerId == $right.vm | summarize disk_count = count() by tostring(name), location, resourceGroup, subscriptionId, tostring(properties.hardwareProfile.vmSize), tostring(properties.storageProfile.imageReference.offer), tostring(properties.osProfile.computerName)"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/aro.json
[   
    {
        "id": "aro01",
        "label": "ARO",
        "description": "Azure Red Hat OpenShift",
        "usecases": [
            "AGPS"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.redhatopenshift/openshiftclusters' | mv-expand wp = properties.workerProfiles | extend nodeName = wp.name, nodeSize = wp.vmSize | project subscriptionId, resourceGroup, name, location, version = properties.clusterProfile.version, nodeName, nodeSize, tags"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/storage-anf.json
[
    {
        "id": "anf01",
        "label": "ANFFillLevel",
        "description": "Get list of ANF volumes for fill level analysis",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.netapp/netappaccounts/capacitypools/volumes' | project name, id, size=properties.usageThreshold, tier=properties.serviceLevel | order by name"
    },
    {
        "id": "anf02",
        "label": "ANFVolumeSizes",
        "description": "Show NetApp accounts, pools, volumes and their sizes",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.netapp/netappaccounts/capacitypools/volumes' | project subscriptionId, resourceGroup, location, name, account = split(name, '/')[0], pool = split(name, '/')[1], volume = split(name, '/')[2], tier = properties.serviceLevel, sizeTB = properties.usageThreshold/1024/1024/1024, tags"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/network-nsg.json
[
    {
        "id": "nsg01",
        "label": "NSGRules",
        "description": "List NSGs with the number of default and customer rules",
        "usecases": [
            "WASA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/networksecuritygroups' | extend defaultRulesCount = array_length(properties.defaultSecurityRules), customerRulesCount = array_length(properties.securityRules) | project subscriptionId, resourceGroup, location, name, defaultRulesCount, customerRulesCount"
    },
    {
        "id": "nsg02",
        "label": "NSGRuleNames",
        "description": "List NSGs with names of the rules",
        "usecases": [
            "WASA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/networksecuritygroups' | mv-expand rules = array_concat(properties.securityRules, properties.defaultSecurityRules) | mv-expand ruleName = rules.name, ruleDirection = rules.properties.direction, rulePriority = rules.properties.priority | project subscriptionId, resourceGroup, location, nsgName = name, ruleName, ruleDirection, rulePriority"
    },
    {
        "id": "nsg03",
        "label": "SubnetNSGAssociations",
        "description": "List all subnets with their NSG associations",
        "usecases": [
            "WASA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/virtualnetworks' | mv-expand sn = properties.subnets | extend subnetName = sn.name | extend nsgName = split(sn.properties.networkSecurityGroup.id, '/')[-1] | project subscriptionId, resourceGroup, location, vnetName = name, subnetName, nsgName"
    },
    {
        "id": "nsg04",
        "label": "UnusedNSG",
        "description": "Show unused NSGs",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/networksecuritygroups' | where properties['subnets'][0]['id'] == '' and properties['networkInterfaces'][0]['id'] == ''"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/network.json
[
    {
        "id": "pip01",
        "label": "PublicIPRedundancy",
        "description": "Show public IP addresses and their redundancy settings",
        "usecases": [
            "WARA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/publicipaddresses' | extend skuName = tostring(sku.name), skuTier = tostring(sku.tier), zones = tostring(zones) | project subscriptionId, resourceGroup, name, location, skuName, skuTier, zones = iif(zones == '', 'None', zones)"
    },
    {
        "id": "nic01",
        "label": "UnattachedNICs",
        "description": "Show unattached NICs (note: some NICs not attached to VMs may still be in use, e.g., private endpoints)",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/networkinterfaces' and isempty(properties.virtualMachine.id)"
    },
    {
        "id": "pip02",
        "label": "UnattachedPublicIPs",
        "description": "Show unattached public IPs",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/publicipaddresses' and isempty(properties.ipConfiguration.id)"
    },
    {
        "id": "vn01",
        "label": "VNETOverview",
        "description": "Show VNETs with their address spaces, subnets, and NSGs",
        "usecases": [],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Network/virtualNetworks' | where subscriptionId in ( '7512593c-5721-4acc-a276-f5976e03b17a') | extend addressSpace = properties.addressSpace.addressPrefixes | mvexpand addressSpace | extend subnets = properties.subnets | mvexpand subnets | extend subnetName = tostring(subnets.name), subnetAddressPrefix = tostring(subnets.properties.addressPrefix), nsgId = tostring(subnets.properties.networkSecurityGroup.id) | project vnetName = name, addressSpace, subnetName, subnetAddressPrefix, nsgName = split(nsgId, '/')[-1]"
    },
    {
        "id": "vn02",
        "label": "VNETDDoS",
        "description": "Show VNETs with their DDoS protection settings",
        "usecases": [
            "WASA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Network/virtualNetworks' | extend ddosProtectionPlan = properties.enableDdosProtection, ddosProtectionPlanId = properties.ddosProtectionPlan.id | project subscriptionId, resourceGroup, vnetName = name, location, ddosProtectionPlan, ddosProtectionPlanId"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/compute-vm.json
[
    {
        "id": "vm01",
        "label": "VMSummary",
        "description": "Azure Virtual Machines",
        "usecases": [
            "WARA",
            "SAPWARR",
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | summarize count() by tostring(properties.hardwareProfile.vmSize) | order by count_ desc"
    },
    {
        "id": "vm02",
        "label": "VMSSSummary",
        "description": "Azure Virtual Machine Scale Sets",
        "usecases": [
            "WARA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachineScaleSets' | extend zones = tostring(zones) | extend zones = iif(zones == '', 'None', zones) | project subscriptionId, resourceGroup, name, location, zones"
    },
    {
        "id": "vm03",
        "label": "VMRedundancy",
        "description": "Azure Virtual Machines Redundancy",
        "usecases": [
            "WARA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | extend availabilitySet = split(properties.availabilitySet.id, '/')[-1], availabilityZone = parse_json(zones)[0], vmSize = properties.hardwareProfile.vmSize, PPG = split(properties.proximityPlacementGroup.id, '/')[2] | project subscriptionId, resourceGroup, name, location, vmSize, avSet = iif(availabilitySet == '', 'None', availabilitySet), avZone = iif(availabilityZone == '', 'None', availabilityZone), ppg = iif(PPG == '', 'None', PPG)"
    },
    {
        "id": "vm04",
        "label": "VMEncryption",
        "description": "Azure Virtual Machines Encryption at host",
        "usecases": [
            "WASA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | extend encryptionAtHost = iif(properties.securityProfile.encryptionAtHost == 'true', 'true', 'false') | project subscriptionId, resourceGroup, name, location, encryptionAtHost"
    },
    {
        "id": "vm05",
        "label": "VMBootDiagnostics",
        "description": "Azure Virtual Machines Boot Diagnostics",
        "usecases": [
            "WARA",
            "SAPWARR",
            "WASA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | extend bootDiagnostics = properties.diagnosticsProfile.bootDiagnostics.enabled | project subscriptionId, resourceGroup, name, location, bootDiagnostics"
    },
    {
        "id": "vm06",
        "label": "VMAcceleratedNetworking",
        "description": "Azure Virtual Machines Accelerated Networking",
        "usecases": [
            "WAPA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | extend vmId = tolower(id) | join kind=inner (resources | where type =~ 'Microsoft.Network/networkInterfaces' | extend enableAcceleratedNetworking = properties.enableAcceleratedNetworking | extend ip = properties.ipConfigurations[0].properties.privateIPAddress | project nicName = split(id, '/')[-1], vmId = tolower(tostring(properties.virtualMachine.id)), ip, enableAcceleratedNetworking) on $left.vmId == $right.vmId | project subscriptionId, resourceGroup, vmName = name, nicName, ip, enableAcceleratedNetworking"
    },
    {
        "id": "vm07",
        "label": "VMDiskSettings",
        "description": "Azure Virtual Machine Disk Settings",
        "usecases": [
            "WAPA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Compute/virtualMachines' | extend datadisks = properties.storageProfile.dataDisks | mvexpand datadisks | project subscriptionId, resourceGroup, vmName = name, location, vmtype = properties.hardwareProfile.vmSize, osdisktype = properties.storageProfile.osDisk.managedDisk.storageAccountType, osdisksize = properties.storageProfile.osDisk.diskSizeGB, osdiskcaching = properties.storageProfile.osDisk.caching, datadiskname = datadisks.name, datadisktype = datadisks.managedDisk.storageAccountType, datadisksize = datadisks.diskSizeGB, datadiskcaching = datadisks.caching"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/appsvc.json
[   
    {
        "id": "asv01",
        "label": "AppServices",
        "description": "App Services",
        "usecases": [
            "WARA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.web/sites' | extend instanceCount = toint(properties.siteConfig.numberOfWorkers) | extend inASE = isnotnull(properties.hostingEnvironmentProfile) | project subscriptionId, resourceGroup, name, location, instanceCount, inASE"
    },
    {
        "id": "asv02",
        "label": "AppServicePlans",
        "description": "App Service Plans",
        "usecases": [
            "WARA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'Microsoft.Web/serverfarms' | extend zoneRedundant = tostring(properties.zoneRedundant) | project subscriptionId, resourceGroup, name, location, zoneRedundant"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/network-ervpn.json
[
    {
        "id": "ervpn01",
        "label": "ExpressRouteCircuits",
        "description": "Show ExpressRoute circuits",
        "usecases": [
            "WARA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/expressroutecircuits' | project circuitName = name, circuitId = id, location, resourceGroup"
    },
    {
        "id": "ervpn02",
        "label": "ExpressRouteGateways",
        "description": "Show ER/VPN gateways",
        "usecases": [
            "WARA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/virtualnetworkgateways' | project subscriptionId, resourceGroup, name, location, sku = properties.sku.name, type = properties.gatewayType"
    },
    {
        "id": "ervpn03",
        "label": "ERConnections",
        "description": "Show interconnections between ExpressRoute circuits and gateways",
        "usecases": [
            "WARA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/connections' | extend circuitId = tostring(properties.expressRouteCircuit.id), gatewayId = tostring(properties.expressRouteGateway.id) | project connectionName = name, circuitId, gatewayId"
    }
]
