=== dohughes-msft/azure-public/rge/agps/schema/query.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "id",
            "label",
            "description",
            "usecases",
            "table",
            "queryBody"
        ],
        "properties": {
            "id": {
                "type": "string"
            },
            "label": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "usecases": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "table": {
                "type": "string"
            },
            "queryBody": {
                "type": "string"
            }
        },
        "additionalProperties": false
    }
}

=== dohughes-msft/azure-public/rge/agps/kql-json/keyvault.json
[
    {
        "id": "kv01",
        "label": "KeyVault",
        "description": "Azure Key Vaults",
        "usecases": [
            "WARA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.keyvault/vaults' | project subscriptionId, resourceGroup, name, location, sku = properties.sku.name"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/01_general.json
[
    {
        "id": "gen01",
        "label": "AllResources",
        "description": "Show all resources",
        "usecases": [
            "WARA",
            "WACOA",
            "SAPWARR",
            "WAPA",
            "WASA",
            "AGPS"
        ],
        "table": "resources",
        "queryBody": "| project subscriptionId, name, type, location"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/backup.json
[   
    {
        "id": "rsv01",
        "label": "RecoveryVaults",
        "description": "Azure Recovery Services Vaults",
        "usecases": [
            "WACOA",
            "WARA",
            "SAPWARR",
            "WASA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.recoveryservices/vaults' | extend sku = tostring(properties.redundancySettings.standardTierStorageRedundancy) | project subscriptionId, resourceGroup, location, name, sku"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/network-lb.json
[
    {
        "id": "lb01",
        "label": "LoadBalancerZones",
        "description": "Show load balancers and their zone settings",
        "usecases": [
            "WARA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/loadbalancers' | mv-expand fipc = properties.frontendIPConfigurations | extend IPConfigName = fipc.name | extend zones = tostring(fipc.zones) | project subscriptionId, resourceGroup, name, IPConfigName, zones = iif(zones == '', 'None', zones)"
    },
    {
        "id": "lb02",
        "label": "LoadBalancerIdleTimeout",
        "description": "List load balancers and their idle timeout settings",
        "usecases": [
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/loadbalancers' | mv-expand lbr = properties.loadBalancingRules | extend ruleName = lbr.name, idleTimeout = lbr.properties.idleTimeoutInMinutes | project subscriptionId, resourceGroup, location, lbName = name, ruleName, idleTimeout"
    },
    {
        "id": "lb03",
        "label": "LoadBalancerEmptyBackend",
        "description": "Show load balancers with empty backend pool",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.network/loadbalancers' and isempty(properties.backendAddressPools[0].properties.backendAddresses[0])"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/network-appgw.json
[
    {
        "id": "agw01",
        "label": "AppGw",
        "description": "Azure Application Gateways",
        "usecases": [
            "WARA",
            "SAPWARR"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.network/applicationgateways' | extend avZones = strcat_array(zones, ',') | extend gatewayType = properties.sku.tier | project subscriptionId, resourceGroup, name, location, sku = properties.sku.name, avZones, gatewayType"
    },
    {
        "id": "agw02",
        "label": "AppGwEmptyBackendPool",
        "description": "Application Gateways with empty backend pool",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type =~ 'microsoft.network/applicationgateways' | where isempty(properties.backendAddressPools[0].properties.backendAddresses[0])"
    }
]

=== dohughes-msft/azure-public/rge/agps/kql-json/storage.json
[
    {
        "id": "stg01",
        "label": "StorageAccountsSKU",
        "description": "List storage accounts together with their SKU",
        "usecases": [
            "WAPA",
            "WARA",
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.storage/storageaccounts' | extend sku = tostring(sku.name) | project subscriptionId, resourceGroup, name, location, kind, sku"
    },
    {
        "id": "stg02",
        "label": "StorageAccountPremium",
        "description": "Show premium blob/file storage accounts",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.storage/storageaccounts' and tostring(sku.name) matches regex ('Premium*')"
    },
    {
        "id": "stg03",
        "label": "StorageAccountLCM",
        "description": "Show storage accounts without any lifecycle management policies",
        "usecases": [
            "WACOA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.storage/storageaccounts' | extend subId = tostring(split(id, '/', 2)[0]), resourceGroup = tostring(split(id, '/', 4)[0]) | project subId, resourceGroup, name | join kind=leftouter (resources | where type == 'microsoft.storage/storageaccounts/managementPolicies' | extend subId = tostring(split(id, '/', 2)[0]), resourceGroup = tostring(split(id, '/', 4)[0]) | project subId, resourceGroup, name) on subId, resourceGroup, name | where isnull(name1)"
    },
    {
        "id": "stg04",
        "label": "StorageAccountSecurity",
        "description": "Storage account security settings (public network access, TLS, allowed clients, HTTPS only)",
        "usecases": [
            "WASA"
        ],
        "table": "resources",
        "queryBody": "| where type == 'microsoft.storage/storageaccounts' | extend publicNetworkAccess = iif(properties.publicNetworkAccess == 'Disabled', 'Disabled', 'Enabled'), minimumTlsVersion = tostring(properties.minimumTlsVersion), clients = array_length(properties.networkAcls.ipRules), httpsOnly = properties.supportsHttpsTrafficOnly | extend allowedClients = iff(clients==0,'All',tostring(clients)) | project subscriptionId, resourceGroup, name, location, kind, skuName = sku.name, publicNetworkAccess, allowedClients, minimumTlsVersion, httpsOnly"
    }
]
